/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Validator;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.DB;
import java.util.Calendar;
import java.util.GregorianCalendar;
import model.EmpId;

/**
 *
 * @author MSI-GF63
 */
public class login extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        runLetters();
        currentTime();
        con = DB.createConnection();
    }

    public void currentTime() {
        Calendar cal = new GregorianCalendar();
        int seconds = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR_OF_DAY);

        lblTime.setText("Current Time : " + hour + ":" + minute + ":" + seconds);
    }

    void runLetters() {
        Thread t = new Thread() {
            @Override
            public void run() {
                String names[] = {"E", "M", "P", "L", "O", "Y", "E", "E", " ", "&", " ", "P", "A", "Y", "R", "O", "L", "L", " ", "M", "A", "N", "A", "G", "E", "M", "E", "N", "T" , " ", "S", "Y", "S", "T", "E", "M"};
                while (true) {
                    String title = "";
                    for (int i = 0; i < names.length; i++) {
                        title = title + names[i];
                        try {
                            setTitle(title);
                            Thread.sleep(200);
                        } catch (Exception e) {

                        }
                    }
                }
            }
        };
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmbDivision = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        lblSugnUp = new javax.swing.JLabel();
        lblResetPassword = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 20)); // NOI18N
        jLabel1.setText("USER Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 160, 33);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/user_100px (Custom).png"))); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 120, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/password_52px (Custom).png"))); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 190, 120, 23);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/department_48px (Custom).png"))); // NOI18N
        jLabel5.setText("Division");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 270, 120, 23);

        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(10, 140, 370, 31);

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(10, 220, 370, 31);

        cmbDivision.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(cmbDivision);
        cmbDivision.setBounds(10, 300, 370, 31);

        btnLogin.setBackground(new java.awt.Color(250, 174, 116));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(180, 370, 113, 40);

        lblSugnUp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblSugnUp.setForeground(new java.awt.Color(250, 174, 116));
        lblSugnUp.setText("Sign Up");
        lblSugnUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSugnUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSugnUpMouseClicked(evt);
            }
        });
        jPanel1.add(lblSugnUp);
        lblSugnUp.setBounds(90, 380, 70, 23);

        lblResetPassword.setFont(new java.awt.Font("Century Gothic", 3, 17)); // NOI18N
        lblResetPassword.setForeground(new java.awt.Color(195, 57, 57));
        lblResetPassword.setText("Forgot your password?");
        lblResetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(lblResetPassword);
        lblResetPassword.setBounds(100, 440, 200, 21);

        jPanel2.setPreferredSize(new java.awt.Dimension(491, 491));

        lblTime.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/toppng.com-alpha-wolf-nutrition-alpha-wolf-company-logo-484x441.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBackground)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBackground)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String uName = txtUsername.getText();
        String passwd = txtPassword.getText();
        String division = cmbDivision.getSelectedItem().toString();
        
        if (Validator.LoginValidation(uName, passwd)) {

            String sql = "SELECT ID, USERNAME, PASSWORD, DIVISION FROM USERS WHERE (USERNAME=? AND PASSWORD=? AND DIVISION=?)";
            try {

                pst = con.prepareStatement(sql);
                pst.setString(1, uName);
                pst.setString(2, passwd);
                pst.setString(3, division);

                rs = pst.executeQuery();

                if (rs.next()) {
                    int id = rs.getInt(1);
                    EmpId.empId = id;
                    String userName = rs.getString("username");
                    EmpId.empName = userName;

                    JOptionPane.showMessageDialog(null, "Login success", "Information", JOptionPane.INFORMATION_MESSAGE);
                    MainMenu mainMenu = new MainMenu();
                    mainMenu.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect login details", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {

                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblSugnUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSugnUpMouseClicked
        SignUp signup = new SignUp(this, true);
        signup.setLocationRelativeTo(this);
        signup.setVisible(true);
    }//GEN-LAST:event_lblSugnUpMouseClicked

    private void lblResetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetPasswordMouseClicked
        ResetPassword resetPassword = new ResetPassword(this, true);
        resetPassword.setLocationRelativeTo(this);
        resetPassword.setVisible(true);
    }//GEN-LAST:event_lblResetPasswordMouseClicked

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        
    }//GEN-LAST:event_btnLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblResetPassword;
    private javax.swing.JLabel lblSugnUp;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
