/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.EmpId;
import controller.Reports;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import model.DB;

/**
 *
 * @author MSI-GF63
 */
public class MainMenu extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        con = DB.createConnection();
        lblEname.setText(String.valueOf(EmpId.empName).toString());
        runLetters();

        dashboardStaffInfo();
        dashboardUser();
    }
    
    void runLetters() {
        Thread t = new Thread() {
            @Override
            public void run() {
                String names[] = {"E", "M", "P", "L", "O", "Y", "E", "E", " ", "&", " ", "P", "A", "Y", "R", "O", "L", "L", " ", "M", "A", "N", "A", "G", "E", "M", "E", "N", "T" , " ", "S", "Y", "S", "T", "E", "M"};
                while (true) {
                    String title = "";
                    for (int i = 0; i < names.length; i++) {
                        title = title + names[i];
                        try {
                            setTitle(title);
                            Thread.sleep(200);
                        } catch (Exception e) {

                        }
                    }
                }
            }
        };
        t.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblEname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnViewEmployees = new javax.swing.JButton();
        btnAddNewEmployee = new javax.swing.JButton();
        btnManageUserInfo = new javax.swing.JButton();
        btnUpdateSalaryInfo = new javax.swing.JButton();
        btnAllowances = new javax.swing.JButton();
        btnDeductions = new javax.swing.JButton();
        pbarMale = new javax.swing.JProgressBar();
        pbarFemale = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pbarAdmin = new javax.swing.JProgressBar();
        pbarUsers = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNoEmps = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNoUsers = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalSalary = new javax.swing.JTextField();
        lblMales = new javax.swing.JLabel();
        lblFemale = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();
        btnViewUsers = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemRefresh = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuItemUpdateSalInfo = new javax.swing.JMenu();
        mnuItemViewUsers = new javax.swing.JMenuItem();
        mnuItemViemEmployees = new javax.swing.JMenuItem();
        mnuItemAddEmployees = new javax.swing.JMenuItem();
        mnuItemManageUserInfo = new javax.swing.JMenuItem();
        mnuItemUpdateSalary = new javax.swing.JMenuItem();
        mnuItemAllowances = new javax.swing.JMenuItem();
        mnuItemDeductions = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mnuItemEmpReport = new javax.swing.JMenuItem();
        mnuItemAllowanceReport = new javax.swing.JMenuItem();
        mnuItemDeductionReport = new javax.swing.JMenuItem();
        mnuItemSalaryReport = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();
        mnuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/exit_60px (Custom).png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(617, 520));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Logged in as :");

        lblEname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEname.setText("Name");

        jLabel3.setFont(new java.awt.Font("Castellar", 1, 20)); // NOI18N
        jLabel3.setText("Dashboard");

        btnViewEmployees.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnViewEmployees.setText("View Employees");
        btnViewEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeesActionPerformed(evt);
            }
        });

        btnAddNewEmployee.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAddNewEmployee.setText("Add New Employee");
        btnAddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmployeeActionPerformed(evt);
            }
        });

        btnManageUserInfo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnManageUserInfo.setText("Manage User Information");
        btnManageUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserInfoActionPerformed(evt);
            }
        });

        btnUpdateSalaryInfo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnUpdateSalaryInfo.setText("Update Salary Information");
        btnUpdateSalaryInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSalaryInfoActionPerformed(evt);
            }
        });

        btnAllowances.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAllowances.setText("Allowances");
        btnAllowances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowancesActionPerformed(evt);
            }
        });

        btnDeductions.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDeductions.setText("Deductions");
        btnDeductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeductionsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Males");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Females");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Admin Users");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Other Users");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Number Of Employees");

        txtNoEmps.setEditable(false);
        txtNoEmps.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Number of Users");

        txtNoUsers.setEditable(false);
        txtNoUsers.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total Salary");

        txtTotalSalary.setEditable(false);
        txtTotalSalary.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        lblMales.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMales.setText("Number Of Males");

        lblFemale.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblFemale.setText("Number Of Females");

        lblAdmin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblAdmin.setText("Number Of Admins");

        lblUsers.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblUsers.setText("Number OF Others");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Average Salary");

        txtAverage.setEditable(false);
        txtAverage.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        btnViewUsers.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnViewUsers.setText("View Users");
        btnViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUsersActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/user_48px (Custom).png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/microsoft_admin_48px (Custom).png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/female_user_52px (Custom).png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/user_60px (Custom).png"))); // NOI18N

        jMenu1.setText("Window");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        mnuItemRefresh.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/synchronize_512px (Custom).png"))); // NOI18N
        mnuItemRefresh.setText("Refresh");
        mnuItemRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRefreshActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemRefresh);

        mnuExit.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/close_window.png"))); // NOI18N
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        mnuItemUpdateSalInfo.setText("Employee");
        mnuItemUpdateSalInfo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        mnuItemViewUsers.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemViewUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/user_100px (Custom).png"))); // NOI18N
        mnuItemViewUsers.setText("View Users");
        mnuItemViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewUsersActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemViewUsers);

        mnuItemViemEmployees.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemViemEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/user_100px (Custom).png"))); // NOI18N
        mnuItemViemEmployees.setText("View Employees");
        mnuItemViemEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViemEmployeesActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemViemEmployees);

        mnuItemAddEmployees.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemAddEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/user_100px (Custom).png"))); // NOI18N
        mnuItemAddEmployees.setText("Add Employees");
        mnuItemAddEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAddEmployeesActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemAddEmployees);

        mnuItemManageUserInfo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemManageUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/resume_60px (Custom).png"))); // NOI18N
        mnuItemManageUserInfo.setText("Manage User Information");
        mnuItemManageUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemManageUserInfoActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemManageUserInfo);

        mnuItemUpdateSalary.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemUpdateSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/salary_female_60px (Custom).png"))); // NOI18N
        mnuItemUpdateSalary.setText("Update Salary Information");
        mnuItemUpdateSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUpdateSalaryActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemUpdateSalary);

        mnuItemAllowances.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemAllowances.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/receive_cash_60px (Custom).png"))); // NOI18N
        mnuItemAllowances.setText("Allowances");
        mnuItemAllowances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAllowancesActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemAllowances);

        mnuItemDeductions.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemDeductions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/minus_52px (Custom).png"))); // NOI18N
        mnuItemDeductions.setText("Deductions");
        mnuItemDeductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDeductionsActionPerformed(evt);
            }
        });
        mnuItemUpdateSalInfo.add(mnuItemDeductions);

        jMenuBar1.add(mnuItemUpdateSalInfo);

        mnuReports.setText("Reports");
        mnuReports.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        mnuItemEmpReport.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemEmpReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/report_file_128px (Custom).png"))); // NOI18N
        mnuItemEmpReport.setText("Employee Report");
        mnuItemEmpReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEmpReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuItemEmpReport);

        mnuItemAllowanceReport.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemAllowanceReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/report_file_128px (Custom).png"))); // NOI18N
        mnuItemAllowanceReport.setText("Employee Allowance Report");
        mnuItemAllowanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAllowanceReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuItemAllowanceReport);

        mnuItemDeductionReport.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemDeductionReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/report_file_128px (Custom).png"))); // NOI18N
        mnuItemDeductionReport.setText("Employee Deduction Report");
        mnuItemDeductionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDeductionReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuItemDeductionReport);

        mnuItemSalaryReport.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemSalaryReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/report_file_128px (Custom).png"))); // NOI18N
        mnuItemSalaryReport.setText("Salary Report");
        mnuItemSalaryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSalaryReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuItemSalaryReport);

        jMenuBar1.add(mnuReports);

        mnuAbout.setText("About");
        mnuAbout.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        mnuItemAbout.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mnuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/Images/about_48px (Custom).png"))); // NOI18N
        mnuItemAbout.setText("About");
        mnuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAboutActionPerformed(evt);
            }
        });
        mnuAbout.add(mnuItemAbout);

        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEname, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddNewEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateSalaryInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAllowances, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pbarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pbarUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pbarMale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAverage)
                                    .addComponent(txtNoEmps)
                                    .addComponent(txtNoUsers)
                                    .addComponent(txtTotalSalary)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pbarFemale, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblEname)
                        .addComponent(jLabel3))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMales)
                                .addComponent(lblFemale)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pbarFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pbarMale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAdmin)
                                .addComponent(lblUsers))
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pbarUsers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbarAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNoEmps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNoUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTotalSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtAverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManageUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateSalaryInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAllowances, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void dashboardStaffInfo() {
        try {
            DecimalFormat df = new DecimalFormat("#.##");
            df.setRoundingMode(RoundingMode.FLOOR);

            //Progress Bars
            int countStaff = 0;
            int countMale = 0;
            int countFemale = 0;

            String sqlStaff = "SELECT COUNT(gender) AS staff FROM staff_information";
            pst = con.prepareStatement(sqlStaff);
            rs = pst.executeQuery();
            if (rs.next());
            countStaff = rs.getInt("staff");
            rs.close();
            pst.close();

            String sqlMale = "SELECT COUNT(gender) AS male FROM staff_information WHERE gender=?";
            pst = con.prepareStatement(sqlMale);
            pst.setString(1, "male");
            rs = pst.executeQuery();
            if (rs.next());
            countMale = rs.getInt("male");
            rs.close();
            pst.close();

            String sqlFemale = "SELECT COUNT(id) AS female FROM staff_information WHERE gender=?";
            pst = con.prepareStatement(sqlFemale);
            pst.setString(1, "female");
            rs = pst.executeQuery();
            if (rs.next());
            countFemale = rs.getInt("female");
            rs.close();
            pst.close();

            lblMales.setText("No. Of Males: "+String.valueOf(countMale));
            lblFemale.setText("No. Of Females: "+String.valueOf(countFemale));

            double countDoubleMale = (double) countMale;
            double countDoubleFemale = (double) countFemale;
            double countDoubleStaff = (double) countStaff;
            double divMale = countDoubleMale / countDoubleStaff * 100;
            double divFemale = countDoubleFemale / countDoubleStaff * 100;

            int pbarMale = (int) divMale;
            this.pbarMale.setValue(pbarMale);

            int pbarFemale = (int) divFemale;
            this.pbarFemale.setValue(pbarFemale);

            //Text Fields
            int countEmp = 0;
            String sqlEmpNo = "SELECT COUNT(id) AS empNo FROM staff_information";
            pst = con.prepareStatement(sqlEmpNo);
            rs = pst.executeQuery();
            if (rs.next());
            countEmp = rs.getInt("empNo");
            rs.close();
            pst.close();
            txtNoEmps.setText(String.valueOf(countEmp));

            double totalSal = 0;
            String sqlSumSal = "SELECT SUM(salary) AS sumSal FROM staff_information";
            pst = con.prepareStatement(sqlSumSal);
            rs = pst.executeQuery();
            if (rs.next());
            totalSal = rs.getDouble("sumSal");
            rs.close();
            pst.close();
            txtTotalSalary.setText(String.valueOf(df.format(totalSal)));

            double avgSal = 0;
            String sqlAvgSal = "SELECT AVG(salary) AS avgSal FROM staff_information";
            pst = con.prepareStatement(sqlAvgSal);
            rs = pst.executeQuery();
            if (rs.next());
            avgSal = rs.getDouble("avgSal");
            rs.close();
            pst.close();
            txtAverage.setText(String.valueOf(df.format(avgSal)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void dashboardUser() {
        try {
            //Progress Bars
            int countAll = 1;
            int countAdmin = 1;
            int countUser = 1;

            String sqlAll = "SELECT COUNT(division) AS allusers FROM users";
            pst = con.prepareStatement(sqlAll);
            rs = pst.executeQuery();
            if (rs.next());
            countAll = rs.getInt("allusers");
            rs.close();
            pst.close();
            
            String sqlAdmin = "SELECT COUNT(division) AS admin FROM users WHERE division=?";
            pst = con.prepareStatement(sqlAdmin);
            pst.setString(1, "Admin");
            rs = pst.executeQuery();
            if (rs.next());
            countAdmin = rs.getInt("admin");
            rs.close();
            pst.close();
            
            String sqlUser = "SELECT COUNT(division) AS user FROM users WHERE division=?";
            pst = con.prepareStatement(sqlUser);
            pst.setString(1, "User");
            rs = pst.executeQuery();
            if (rs.next());
            countUser = rs.getInt("user");
            rs.close();
            pst.close();              
            
            lblAdmin.setText("No. Of Admins: "+String.valueOf(countAdmin));
            lblUsers.setText("No. Of Other Users: "+String.valueOf(countUser));
            
            double countDoubleAll = (double)countAll;
            double countDoubleAdmin = (double) countAdmin;
            double countDoubleUser = (double) countUser;
            double divAdmin = countDoubleAdmin / countDoubleAll * 100;
            double divUser = countDoubleUser / countDoubleAll * 100;

            int pbarAdmin = (int) divAdmin;
            this.pbarAdmin.setValue(pbarAdmin);

            int pbarUser = (int) divUser;
            this.pbarUsers.setValue(pbarUser);    
            
            
            //Text Fields
            int noUsers = 0;
            String sqlNoUsers = "SELECT COUNT(id) AS noUsers FROM users";
            pst = con.prepareStatement(sqlNoUsers);
            rs = pst.executeQuery();
            if (rs.next());
            noUsers = rs.getInt("noUsers");
            rs.close();
            pst.close();            
            txtNoUsers.setText(String.valueOf(noUsers));

        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }


    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure to logout", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirmation == 0) {
            login login = new login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void mnuItemEmpReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEmpReportActionPerformed
        Reports.EmployeeReport();
    }//GEN-LAST:event_mnuItemEmpReportActionPerformed

    private void mnuItemAllowanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAllowanceReportActionPerformed
        Reports.AllowanceReport();
    }//GEN-LAST:event_mnuItemAllowanceReportActionPerformed

    private void mnuItemDeductionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDeductionReportActionPerformed
        Reports.DeductionReport();
    }//GEN-LAST:event_mnuItemDeductionReportActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirmation == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuItemViemEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViemEmployeesActionPerformed
        ViewEmployee obj = new ViewEmployee();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemViemEmployeesActionPerformed

    private void mnuItemAddEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAddEmployeesActionPerformed
        AddEmployee obj = new AddEmployee();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemAddEmployeesActionPerformed

    private void mnuItemManageUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemManageUserInfoActionPerformed
        UpdateUserDetails obj = new UpdateUserDetails();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemManageUserInfoActionPerformed

    private void mnuItemUpdateSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUpdateSalaryActionPerformed
        UpdateSalary obj = new UpdateSalary();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemUpdateSalaryActionPerformed

    private void mnuItemAllowancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAllowancesActionPerformed
        Allowance obj = new Allowance();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemAllowancesActionPerformed

    private void mnuItemDeductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDeductionsActionPerformed
        Deduction obj = new Deduction();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemDeductionsActionPerformed

    private void mnuItemSalaryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSalaryReportActionPerformed
        SalaryReport obj = new SalaryReport();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemSalaryReportActionPerformed

    private void btnViewEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeesActionPerformed
        ViewEmployee obj = new ViewEmployee();
        obj.setVisible(true);
    }//GEN-LAST:event_btnViewEmployeesActionPerformed

    private void btnAddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmployeeActionPerformed
        AddEmployee obj = new AddEmployee();
        obj.setVisible(true);
    }//GEN-LAST:event_btnAddNewEmployeeActionPerformed

    private void btnManageUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserInfoActionPerformed
        UpdateUserDetails obj = new UpdateUserDetails();
        obj.setVisible(true);
    }//GEN-LAST:event_btnManageUserInfoActionPerformed

    private void btnUpdateSalaryInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSalaryInfoActionPerformed
        UpdateSalary obj = new UpdateSalary();
        obj.setVisible(true);
    }//GEN-LAST:event_btnUpdateSalaryInfoActionPerformed

    private void btnAllowancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowancesActionPerformed
        Allowance obj = new Allowance();
        obj.setVisible(true);
    }//GEN-LAST:event_btnAllowancesActionPerformed

    private void btnDeductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeductionsActionPerformed
        Deduction obj = new Deduction();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDeductionsActionPerformed

    private void mnuItemViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewUsersActionPerformed
        ViewUsers obj = new ViewUsers();
        obj.setVisible(true);
    }//GEN-LAST:event_mnuItemViewUsersActionPerformed

    private void btnViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUsersActionPerformed
        ViewUsers obj = new ViewUsers();
        obj.setVisible(true);
    }//GEN-LAST:event_btnViewUsersActionPerformed

    private void mnuItemRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRefreshActionPerformed
        MainMenu obj = new MainMenu();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemRefreshActionPerformed

    private void mnuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAboutActionPerformed
        About about = new About(this, true);
        about.setLocationRelativeTo(this);
        about.setVisible(true);
    }//GEN-LAST:event_mnuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmployee;
    private javax.swing.JButton btnAllowances;
    private javax.swing.JButton btnDeductions;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageUserInfo;
    private javax.swing.JButton btnUpdateSalaryInfo;
    private javax.swing.JButton btnViewEmployees;
    private javax.swing.JButton btnViewUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblEname;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblMales;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuItemAbout;
    private javax.swing.JMenuItem mnuItemAddEmployees;
    private javax.swing.JMenuItem mnuItemAllowanceReport;
    private javax.swing.JMenuItem mnuItemAllowances;
    private javax.swing.JMenuItem mnuItemDeductionReport;
    private javax.swing.JMenuItem mnuItemDeductions;
    private javax.swing.JMenuItem mnuItemEmpReport;
    private javax.swing.JMenuItem mnuItemManageUserInfo;
    private javax.swing.JMenuItem mnuItemRefresh;
    private javax.swing.JMenuItem mnuItemSalaryReport;
    private javax.swing.JMenu mnuItemUpdateSalInfo;
    private javax.swing.JMenuItem mnuItemUpdateSalary;
    private javax.swing.JMenuItem mnuItemViemEmployees;
    private javax.swing.JMenuItem mnuItemViewUsers;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JProgressBar pbarAdmin;
    private javax.swing.JProgressBar pbarFemale;
    private javax.swing.JProgressBar pbarMale;
    private javax.swing.JProgressBar pbarUsers;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtNoEmps;
    private javax.swing.JTextField txtNoUsers;
    private javax.swing.JTextField txtTotalSalary;
    // End of variables declaration//GEN-END:variables
}
