/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.DB;

/**
 *
 * @author MSI-GF63
 */
public class UpdateSalary extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form UpdateSalary
     */
    public UpdateSalary() {
        initComponents();
        con = DB.createConnection();
        setTitle("Employee & Payroll Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSalaryBy = new javax.swing.ButtonGroup();
        btnGroupMethod = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchEID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtBasicSal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbnPercentage = new javax.swing.JRadioButton();
        rbnAmount = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPercentage = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        rbnIncrement = new javax.swing.JRadioButton();
        rbnDecrement = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 20)); // NOI18N
        jLabel1.setText("Update salary");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Employee Id");

        txtSearchEID.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtSearchEID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchEIDKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Basic Salary");

        txtFirstName.setEditable(false);
        txtFirstName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        txtLastName.setEditable(false);
        txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        txtDepartment.setEditable(false);
        txtDepartment.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        txtBasicSal.setEditable(false);
        txtBasicSal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Update Salary By");

        btnGroupSalaryBy.add(rbnPercentage);
        rbnPercentage.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rbnPercentage.setSelected(true);
        rbnPercentage.setText("Percentage %");
        rbnPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnPercentageActionPerformed(evt);
            }
        });

        btnGroupSalaryBy.add(rbnAmount);
        rbnAmount.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rbnAmount.setText("Amount");
        rbnAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAmountActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Percentage %");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Amount");

        txtPercentage.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        txtAmount.setEditable(false);
        txtAmount.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        btnClear.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Method");

        btnGroupMethod.add(rbnIncrement);
        rbnIncrement.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rbnIncrement.setSelected(true);
        rbnIncrement.setText("Increment");

        btnGroupMethod.add(rbnDecrement);
        rbnDecrement.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rbnDecrement.setText("Decrement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtDepartment)
                            .addComponent(txtBasicSal)
                            .addComponent(txtSearchEID)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbnPercentage)
                                .addGap(18, 18, 18)
                                .addComponent(rbnAmount))
                            .addComponent(txtPercentage)
                            .addComponent(txtAmount)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbnIncrement)
                                .addGap(18, 18, 18)
                                .addComponent(rbnDecrement))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBasicSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbnPercentage)
                    .addComponent(rbnAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbnIncrement)
                    .addComponent(rbnDecrement))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clearData() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtDepartment.setText("");
        txtBasicSal.setText("");
        txtPercentage.setText("");
        txtAmount.setText("");
        txtSearchEID.setText("");
        rbnPercentage.setSelected(true);
        rbnIncrement.setSelected(true);
    }

    private void txtSearchEIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEIDKeyReleased
        try {
            String sql = "SELECT * FROM staff_information WHERE id=?";
            pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtSearchEID.getText()));
            rs = pst.executeQuery();

            if (rs.next());

            String fName = rs.getString("firstName");
            txtFirstName.setText(fName);

            String lName = rs.getString("lastName");
            txtLastName.setText(lName);

            String department = rs.getString("department");
            txtDepartment.setText(department);

            String basicSal = rs.getString("salary");
            txtBasicSal.setText(basicSal);

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_txtSearchEIDKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void rbnPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnPercentageActionPerformed
        txtPercentage.setEditable(true);
        txtAmount.setEditable(false);
        txtAmount.setText(null);
    }//GEN-LAST:event_rbnPercentageActionPerformed

    private void rbnAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAmountActionPerformed
        txtAmount.setEditable(true);
        txtPercentage.setEditable(false);
        txtPercentage.setText(null);
    }//GEN-LAST:event_rbnAmountActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtBasicSal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter employee ID", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to update records?", "Update Records", JOptionPane.YES_NO_OPTION);
            if (confirmation == 0) {
                try {
                    int id = Integer.parseInt(txtSearchEID.getText());

                    double salary = Double.parseDouble(txtBasicSal.getText());
                    double newSalary = salary;

                    if (rbnPercentage.isSelected()) {
                        if (txtPercentage.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please enter percentage value", "Warning", JOptionPane.WARNING_MESSAGE);
                        } else {
                            double percentage = Double.parseDouble(txtPercentage.getText());
                            if (rbnIncrement.isSelected()) {
                                newSalary = salary + (salary * percentage / 100);
                            } else if (rbnDecrement.isSelected()) {
                                newSalary = salary - (salary * percentage / 100);
                            }

                            String sql = "UPDATE staff_information SET salary='" + newSalary + "' WHERE id='" + id + "' ";
                            pst = con.prepareStatement(sql);
                            boolean result = pst.execute();

                            if (result = true) {
                                JOptionPane.showMessageDialog(null, "Salary information updated successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                                clearData();
                            } else {
                                JOptionPane.showMessageDialog(null, "Salary information updation failed", "Error", JOptionPane.ERROR_MESSAGE);
                            }

                        }
                    } else if (rbnAmount.isSelected()) {
                        if (txtAmount.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please enter amount", "Warning", JOptionPane.WARNING_MESSAGE);
                        } else {
                            double amount = Double.parseDouble(txtAmount.getText());
                            if (rbnIncrement.isSelected()) {
                                newSalary = salary + amount;
                            } else if (rbnDecrement.isSelected()) {
                                newSalary = salary - amount;
                            }
                            
                            String sql = "UPDATE staff_information SET salary='" + newSalary + "' WHERE id='" + id + "' ";
                            pst = con.prepareStatement(sql);
                            boolean result = pst.execute();

                            if (result = true) {
                                JOptionPane.showMessageDialog(null, "Salary information updated successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                                clearData();
                            } else {
                                JOptionPane.showMessageDialog(null, "Salary information updation failed", "Error", JOptionPane.ERROR_MESSAGE);
                            }

                        }
                    }

                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGroupMethod;
    private javax.swing.ButtonGroup btnGroupSalaryBy;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbnAmount;
    private javax.swing.JRadioButton rbnDecrement;
    private javax.swing.JRadioButton rbnIncrement;
    private javax.swing.JRadioButton rbnPercentage;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBasicSal;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPercentage;
    private javax.swing.JTextField txtSearchEID;
    // End of variables declaration//GEN-END:variables
}
