/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.DB;

/**
 *
 * @author MSI-GF63
 */
public class ViewEmployee extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form ViewEmployee
     */
    public ViewEmployee() {
        initComponents();
        con = DB.createConnection();
        setTitle("Employee & Payroll Management System");
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchEmpName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewEmployees = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 20)); // NOI18N
        jLabel1.setText("View employees");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Employee Name : ");

        txtSearchEmpName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtSearchEmpName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchEmpNameKeyReleased(evt);
            }
        });

        tblViewEmployees.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblViewEmployees.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblViewEmployees.setRowHeight(30);
        tblViewEmployees.setRowMargin(15);
        jScrollPane1.setViewportView(tblViewEmployees);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchEmpName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTable() {
        try {
            String sql = "SELECT * FROM staff_information";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

                DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"ID", "First Name", "Last Name", "Date of Birth", "Gender", "Email", "Contact", "House No", "Address Line 1", "Address Line 2", "Postal Code", "Department", "Designation", "Date Hired", "Basic Salary", "Job Title", "Status" });

                while (rs.next()) {
                    Vector vec = new Vector();
                    vec.add(rs.getString("id"));
                    vec.add(rs.getString("firstName"));
                    vec.add(rs.getString("lastName"));
                    vec.add(rs.getString("dob"));
                    vec.add(rs.getString("gender"));
                    vec.add(rs.getString("email"));
                    vec.add(rs.getString("contact"));
                    vec.add(rs.getString("houseNo"));
                    vec.add(rs.getString("address1"));
                    vec.add(rs.getString("address2"));
                    vec.add(rs.getString("postalCode"));
                    vec.add(rs.getString("department"));
                    vec.add(rs.getString("designation"));
                    vec.add(rs.getString("dateHired"));
                    vec.add(rs.getString("salary"));
                    vec.add(rs.getString("jobTitle"));
                    vec.add(rs.getString("status"));
                    
                    model.addRow(vec);
                }
                tblViewEmployees.setModel(model);
                
            }
            catch(Exception e){
                    
            }
    }


    private void txtSearchEmpNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEmpNameKeyReleased
       try {        
           String sql = "SELECT * FROM staff_information WHERE firstName LIKE '"+txtSearchEmpName.getText()+"%'";
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           
           
            DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"ID", "First Name", "Last Name", "Date of Birth", "Gender", "Email", "Contact", "House No", "Address Line 1", "Address Line 2", "Postal Code", "Department", "Designation", "Date Hired", "Basic Salary", "Job Title", "Status" });
            
                while (rs.next()) {
                    Vector vec = new Vector();
                    vec.add(rs.getString("id"));
                    vec.add(rs.getString("firstName"));
                    vec.add(rs.getString("lastName"));
                    vec.add(rs.getString("dob"));
                    vec.add(rs.getString("gender"));
                    vec.add(rs.getString("email"));
                    vec.add(rs.getString("contact"));
                    vec.add(rs.getString("houseNo"));
                    vec.add(rs.getString("address1"));
                    vec.add(rs.getString("address2"));
                    vec.add(rs.getString("postalCode"));
                    vec.add(rs.getString("department"));
                    vec.add(rs.getString("designation"));
                    vec.add(rs.getString("dateHired"));
                    vec.add(rs.getString("salary"));
                    vec.add(rs.getString("jobTitle"));
                    vec.add(rs.getString("status"));
                    
                    model.addRow(vec);
                }
            tblViewEmployees.setModel(model);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSearchEmpNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewEmployees;
    private javax.swing.JTextField txtSearchEmpName;
    // End of variables declaration//GEN-END:variables
}
